name: Go Server Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_backend:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd backend
        go build -v -o server ./main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: backend/server
  
  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build
      working-directory: ./frontend

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: vue3-frontend
        path: frontend/dist  # Assuming the built files are in the 'dist' folder

  database_migrations:
    name: Upload Migrations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upload Migration Files
      uses: actions/upload-artifact@v2
      with:
        name: sql-migrations
        path: |
          database/migrations/**/*.sql
